### ISSUE TITLE
Pubspec uses hardcoded local paths

### ISSUE THREAD

**Issue by yissachar** [dotdotcommadot/dart_robotlegs#1]
```
  dotdotcommadot_messaging:
    path: C:\Users\hvk\DartWorkspace\dotdotcommadot_messaging
  robotlegs_di:
    path: C:\Users\hvk\DartWorkspace\robotlegs_di
```

These could be modified to point to the respective Github URLs instead:

```
  dotdotcommadot_messaging:
    git:
      url: git://github.com/dotdotcommadot/dotdotcommadot_messaging
  robotlegs_di:
    git:
      url: git://github.com/dotdotcommadot/dart_robotlegs_di
```

This way robotlegs would run out of the box without any errors. (The same applies for the [robotlegs_polymer example](https://github.com/dotdotcommadot/robotlegs_polymer).)
